<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="modular_bot">

  <!-- Parameters -->
  <xacro:property name="wheel_radius" value="0.05"/>
  <xacro:property name="wheel_width" value="0.02"/>
  <xacro:property name="wheel_separation" value="0.30"/>
  
  <!-- Yellow "material" -->
    <material name="yellow">
    <color rgba="1 1 0 1"/>
  </material>

  <!-- Base Link -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="0.4 0.3 0.1"/>
      </geometry>
    </visual>
    <collision>
      <geometry>
        <box size="0.4 0.3 0.1"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="5.0"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.1" iyy="0.1" izz="0.1"
               ixy="0.0" ixz="0.0" iyz="0.0"/>
    </inertial>
  </link>

  <!-- Left Wheel -->
  <link name="left_wheel_link">
    <visual>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="yellow"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="0.3"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <!-- conservative inertia guess; we can refine later -->
      <inertia ixx="0.0005" iyy="0.0005" izz="0.0005"
              ixy="0.0" ixz="0.0" iyz="0.0"/>
    </inertial>

  </link>


  <!-- Right Wheel -->
  <link name="right_wheel_link">
    <visual>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="yellow"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="0.3"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <!-- conservative inertia guess; we can refine later -->
      <inertia ixx="0.0005" iyy="0.0005" izz="0.0005"
              ixy="0.0" ixz="0.0" iyz="0.0"/>
    </inertial>

  </link>


  <!-- Joints -->
  <joint name="left_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="left_wheel_link"/>
    <origin xyz="0 ${wheel_separation * 0.5 + wheel_width*0.5} -${wheel_radius * 0.5}"/>
    <axis xyz="0 1 0"/>
  </joint>

  <joint name="right_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="right_wheel_link"/>
    <origin xyz="0 -${wheel_separation * 0.5 + wheel_width*0.5} -${wheel_radius * 0.5}"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- Gazebo Harmonic: Thin actuator I/O for wheel joints -->
  <gazebo>
    <plugin filename="gz-sim-joint-controller-system"
            name="gz::sim::systems::JointController">
      <joint_name>left_wheel_joint</joint_name>
    </plugin>

    <plugin filename="gz-sim-joint-controller-system"
            name="gz::sim::systems::JointController">
      <joint_name>right_wheel_joint</joint_name>
    </plugin>
  </gazebo>
</robot>
